name: Docker - docker_fc_pwsh_build image

on:
  workflow_dispatch:
  schedule: 
    - cron: '0 0 * * 0'
  push:
    branches:
      - main  # Trigger CI on main branch
    paths: 
      - 'src/fc_pwsh_build/*'
      - '.github/workflows/build-docker_fc_pwsh_build.yml'
  pull_request:
    branches:
      - main  # Trigger gated pipeline on PR to main
    paths:
      - 'src/fc_pwsh_build/*'
      - '.github/workflows/build-docker_fc_pwsh_build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: brandonmcclure/fc_pwsh_build
  JUST_IMAGE_NAME: fc_pwsh_build

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          username: bmcclure89
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            bmcclure89/${{ env.JUST_IMAGE_NAME }}

      - name: Build Docker image (non main branch)
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        if: github.ref != 'refs/heads/main'
        with:
          context: ./src/fc_pwsh_build
          load: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
      - name: Build and push Docker image (main branch)
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        if: github.ref == 'refs/heads/main'
        with:
          context: ./src/fc_pwsh_build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
      - id: lowercaseImageName
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_NAME }}
      - name: Save Docker Image archive to local filesystem
        run: "docker save --output fc_pwsh_build.tar ${{env.REGISTRY}}/${{ steps.lowercaseImageName.outputs.lowercase }}"
      - name: Upload application's Docker Image as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          path: fc_pwsh_build.tar
          name: fc_pwsh_build.tar
